### PR TITLE
[genPOI] Work around JSON signs

### LINKED ISSUE #1188: unicode character issues from minecraft data (since 1.8?)
I'm using a modified version of the script in the documentation for showing signs as POIs on the map:

    def signFilter(poi):
        if poi['id'] == 'Sign':
            return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])

It appears that many characters are being encoded as unicode strings (`\u0027` instead of an apostrophe for example). It sounds like this is going on in various places as I've seen tickets related to this elsewhere due to the minecraft data files now being in UTF8 format rather than ASCII by default now.

### PR DESCRIPTION
**Pull request by CounterPillow**
Fixes #1188 and #1198 (which is a duplicate of the former but you guys haven't closed it because you're lazy bums)

### CODE REVIEW

**Comment by CounterPillow** [comment]
Apparently this PR is broken because I treat the sign text contents as JSON, when it's actually yaml or some shit like that! Hooray! Of course, everyone in the Minecraft community is too braindead to know the difference between `{"text":"foo"}` and `{text:"foo"}` so they call it "JSON" anyway. Will fix sometime in the future. Maybe.

**Comment by CounterPillow** [comment]
As I've just discovered it's neither YAML nor JSON, it's their own thing apparently, which is so close to JSON you mistake it for JSON if you don't look closely, but it violates the JSON spec just for the fun of it and thus you can't use a JSON parser to parse it. Because why use existing general purpose formats when you can make up your own, even if you've already made up your own! Just make up another one and then store it inside the one everybody already speaks, so they have to go through extra hoops and write a second parser. For literally no reason.

Sorry for being so rant-y, but I have no formal education in the field and have never professionally written code before, but even I can see from a mile away that this is the most ass-backward shit ever.

**Comment by CounterPillow** [comment]
Okay, interesting discovery just now.

Apparently, while what you type into Minecraft to generate it is not JSON, Minecraft seems to actually store it as valid JSON! So my PR is correct?

Here's some libredstone nbttool output:
```
TAG_List("TileEntities"): 1 entries of type TAG_Compound
{
    TAG_Compound: 8 entries
    {
        TAG_Int("x"): 2
        TAG_Int("y"): 104
        TAG_Int("z"): 216
        TAG_String("Text4"): null
        TAG_String("Text3"): null
        TAG_String("Text2"): null
        TAG_String("Text1"): {"extra":["there"],"text":"Hello"}
        TAG_String("id"): Sign
    }
}
```

That is JSON, with the double quotation marks and all.

And again, just to confirm I'm not dreaming, in colour blue:

```
TAG_String("Text1"): {"color":"blue","text":"Hello there"}
```

Yeah so this PR is correct after all, Mojang's non-existent documentation is just not accurate because it doesn't exist.

Feel free to merge.

**Comment by CounterPillow** [comment]
Just fixed another corner case which would spam null's all over our precious signs. The reason for that is that since we do not know whether a sign is JSON or not, "null" might be both the text "null" on a 1.7 sign or just `null` as a JSON value for an empty line. We're now doing what Minecraft does, which is eating all nulls. Refer to the comment in the code if you feel like headdesking at how retarded this shit is. Yes, they're even doing it for lists. No, we don't reproduce that behaviour because it needlessly breaks too much shit from previous versions while never really occurring in JSON signs.

**Comment by agrif** [comment]
*eyes gloss over wall of text*

**Pull request merged**
