### PR TITLE
[py3] Fixes for WindowsOutputStream

### PR DESCRIPTION
**Pull request by eminence**
I spent like 0.4 seconds on this, I'm not sure if this is the right way to do this.

cc @agrif @CounterPillow

### CODE REVIEW

**Comment by agrif** [comment]
This will probably fail on any string that has a unicode character in it, since you call `c.decode()` on a single byte of utf-8. Odd as it seems, you probably want to do this entirely with strings. If you don't get around to it today, maybe I will.

**Comment by eminence** [comment]
This might be dumb, but what about `chr(ord(c))`

**Comment by chungy** [comment]
I don't know what issue is being attempted to be resolved, but in Chocolate Doom I had to use a workaround for Unicode on Windows too: https://github.com/chocolate-doom/chocolate-doom/commit/685062a58f7be4140648dd9c7b4459e34f88cbfa

**Comment by eminence** [comment]
I abandoned the encode/decode nonsense and just switched from `BytesIO` to `StringIO`

**Pull request merged**
