### PR TITLE
Leaflet

### PR DESCRIPTION
**Pull request by eminence**
Do not merge yet.  I opened this PR just so people can track status

Things to do:
- [x] Add a world switcher control
- [x] re-add support for overlays
- [x] re-add support for updating the url hash (so you can copy/paste a URL to link to a specific location)
- [x] I _think_ we still use a few small assets from gmaps?  Check if we do and if so, remove/replace them
- [x] re-add support for showing the chunk/region coords
- [ ] ... what else?

Discussion points:
- We are _totally_ dropping support for the google maps API.  Some of our users might have added some customized stuff to their maps, which will require updating.   In theory, we could support both google maps and leaflet, but I'm not sure I'm in favor of this, just because of the extra work involved.  If anyone has opinions on this, please leave a comment

### CODE REVIEW

**Comment by eminence** [comment]
CC #1308

**Comment by CounterPillow** [comment]
Markers need to be re-implemented too, should be fairly easy and require no changes on the genpoi.py side of things

[ ] reimplement markers in the map
[ ] reimplement marker groups and marker group dialog
[ ] reimplement marker popups
[ ] reimplement polylines
[ ] reimplement "Home" and location markers

**Comment by CounterPillow** [comment]
`control-bg.png` and `control-bg-active.png` in web_assets might or might not be google maps assets, but either way, we likely don't need those with leaflet anymore. (what were they even used for originally? Buttons?)

The home marker and location marker are Google Maps assets which we load externally. I can easily replace those with a bit of fiddling in inkscape, and we can ship them as part of overviewer to further eliminate any dependencies on third party resources.

**Comment by CounterPillow** [comment]
**Warning**: Legal mumbo-jumbo.

I have created a replacement for the `home.png` marker that google maps uses. The design is inspired by the Google Maps icon, but in no step of the creation was the Google Maps icon traced or otherwise used directly, hence, the icon is an original creation based on the base marker templates which I have also authored myself.

To prove that I authored the icon myself, I not only have included the source SVG, but can also  share some behind-the-scenes info of the creation process: The icon was made in Inkscape, which is terribly slow at rendering the smooth shadow effect around the edges, and I had to merge the path of the roof and the path of the house into one path, as SVG renderers don't guarantee any accuracy and will often render non-opaque pixels in places where two lines form a perfect seal in an angle that doesn't align with the pixel grid.

I take sole responsibility for the claim to authorship of the `marker_home.png` and `marker_home.svg` icons contained within the Overviewer source repository being true as of the date of this writing, and anyone objecting to my claim of authorship should take their concerns up to me, and not harass other Overviewer contributors.

**Comment by CounterPillow** [comment]
I also claim authorship for the `marker_location.png` and `marker_location.svg` files inside the Minecraft-Overviewer repository; they are original works and in no way knowingly and directly derived from any Google Maps icons.

In contrast to the Google Maps regroup icon, ours [doesn't rip off the SBB Treffpunkt sign](https://www.sbb.ch/en/content/sbbshop/de/zuerich/09_eg_hh_treffpunkt.html) as blatantly.

**Comment by CounterPillow** [comment]
The TileLayer or whatever needs the option `errorTileUrl` set to blank.png inside whatever the tile url is (e.g. `world-lighting/blank.png`), I'm not familiar enough with leaflet yet to find out what's the prettiest way to restructure the code so we can do that, but I'll let you know of how to get rid of the ugly "Image not found" boxes.

I'm also not sure is how to properly style the added control elements, but adding the CSS classes `leaflet-control-layers leaflet-control-layers-expanded leaflet-control` to the world selector `<select>` DOM element makes it much nicer to look at. Though I suspect leaflet has some built-in way to style things appropriately, maybe.

**Comment by CounterPillow** [comment]
Well then, did the errorTileUrl thing, though I'm not sure whether the way I "build" the path is correct in all circumstances. Can somebody double-check?

Also, two lines below that we still have a reference to "gmap", is that intended?

**Comment by CounterPillow** [comment]
Leaflet layer objects now have a `tileSetConfig` member which gives you access to the tileset's configuration as it is in overviewerConfig.js. Useful for doing things in callbacks.

Also, I've re-implemented the bgcolor setting (simple one-liner). And the spawn marker should now probably also work with rotated worlds.

**Comment by CounterPillow** [comment]
Note on map controls:

- Left-click on location or spawn marker centres view on the respective marker.
- Right-click on location marker dismisses it.

**Comment by LeadMagnet** [comment]
RE comment posted 28 June (sorry, on vacation! :P )

I know you're busy on more important issues, but any chance on adding a feature request while yer in there pulling code apart? Specifically request #1222?

Sneaky plug! :D

**Comment by LeadMagnet** [comment]
How do I run this on a Windows machine? The EXE isn't included.

**Comment by CounterPillow** [comment]
@LeadMagnet You'd have to compile it yourself. Fortunately, you don't have to do this though, because I've just made fresh win32 and win64 builds of the leaflet branch.

* [Windows 32 bit](https://overviewer.org/builds/win32/4/overviewer-0.12.154.zip) (Commit 50e774c)
* [Windows 64 bit](https://overviewer.org/builds/win64/4/overviewer-0.12.154.zip) (Commit 50e774c)

For instructions on how to acquire the source and build it yourself, check out this small gist I made: https://gist.github.com/CounterPillow/92ccc3489f4dc9b8c52eaa73469d513b

Thanks for showing interest!

**Comment by LeadMagnet** [comment]
Thanks CP, appreciate it. Do you want test issues raised in this thread or create standard issues?

**Comment by CounterPillow** [comment]
@LeadMagnet keeping any comments and issues in here is probably the best idea

**Comment by E-PaiN** [comment]
I'm sort of a noob when it comes to github, I'm used to installing stuff via the distro's package manager.
Right now I'm using Overviewer via the PPA repository and I wrote a script to fix the Google key in the index file after each cron job update.

I'd like to ditch anything Google related however.

What's the easiest way for me to switch to this Leaflet branch?

**Comment by CounterPillow** [comment]
@E-PaiN 
First, you need to acquire the source
```
git clone https://github.com/overviewer/Minecraft-Overviewer.git
cd Minecraft-Overviewer
git checkout leaflet
```

Then, you need to build it.
```
python2 setup.py build
```

Now you can use `overviewer.py` in the Minecraft-Overviewer directory to run Overviewer. We recommend **not** to execute "setup.py install" since this will install the git version system-wide without the package management, which can be messy to remove/update. The downside of not doing this is that you don't have overviewer.py in your `$PATH` automatically.

To update the source, use the following:
```
git pull
```
then, re-build.

**Comment by E-PaiN** [comment]
@CounterPillow 
That seemed to have worked like a charm!
I've cleared the output directory just to be sure, and now it's generating the maps for the first time as I type this, I'm so excited!

By the way, is there going to be a separate PPA / distribution system for this, or will the leaflet branch simply replace the Google branch all-together in the future?

**Comment by CounterPillow** [comment]
@E-PaiN 
>By the way, is there going to be a separate PPA / distribution system for this, or will the leaflet branch simply replace the Google branch all-together in the future?

The leaflet branch will be merged into the master branch when it's done, and thus will replace Google Maps entirely.

**Comment by LeadMagnet** [comment]
Have been testing this for a bit. Ran my largest world using it. Total render was 14 hours. (http://188.165.162.243 world 1). Overworld did not render. The GAPI version I always get "error reading region, skipping" on several regions. Didn't happen with this version. The end and nether rendered no problem. Error log reported no errors at all. Can i run it using the --verbose option?

**Comment by mroderick** [comment]
I tried out this branch today, it worked well with my tiny little world.

**Comment by florianjacob** [comment]
works like charm :smile: Thanks!

**Comment by Hell0w** [comment]
Thank you for this Leaflet version !
It works perfectly !

**Comment by sbuller** [comment]
I ran into google maps API key issues, came across this branch, and it is working nicely. Thank you.

**Comment by gigafunk** [comment]
Whats the word? does thi snot build anymore or something?

**Comment by CounterPillow** [comment]
@gigafunk it still does build, but it is worth noting that the 1.12 changes are not in this branch.

The travis-ci error is due to python 2.6's pip, for which I've disabled testing in git master.

**Comment by CWallenberg** [comment]
Any ETA when leaflet is fully working or almost ready for release?

**Comment by CounterPillow** [comment]
@CWallenberg when someone reimplements markers

There's no ETA because none of us are employed to work on Overviewer, so we work when we feel like working on Overviewer, which lately hasn't been all that often.

**Comment by shakurass** [comment]
This is an amazing idea. I've been trying to find a way to integrate an Overviewer map into an Angular-CLI app without using an iframe. I will pull this down and check it out!

**Comment by eminence** [comment]
Based on the discussion in #1308, we've decided to resurrect this leaflet work again and merge it into master.   We think this new version is pretty usable, but there still may be some bugs (for example, the world selector control seems a little buggy in IE and Edge).   Please open a new github issue for any problems or bugs you find.  

The http://overviewer.org/downloads page is in the process of being updated with the latest builds.

Thank you all for your patience over the past 2 years!

**Pull request merged**
