### PR TITLE
addressing genPOI RAM usage

### PR DESCRIPTION
**Pull request by MasterofJOKers**
I've had some trouble lately with running `overviewer.py --genpoi` resulting in an OOM-kill of our minecraft server. The problem seems to me the one described under #1090 1. Every Entity and TileEntity is read into memory and only later filtered. This should be changed and filtering should be done on the fly.

I have implemented a solution that works on my server. I haven't tested it anywhere else and I only generate signs, so manual POIs and Players are not tested, though that code was changed, too.

The first couple of commits are just some cleanups on my way to understanding, what the code does. Feel free to squash them, if you consider this code as good enough to be merged.

### CODE REVIEW

**Comment by MasterofJOKers** [comment]
and again updated to latest master, to include changes made to genPoy.py by 77c4d24660fd1682eb496c600340142904a56989 and f1af25799e84893d96c0e667930c9339569ab794

**Comment by agrif** [comment]
Just an update here, we've been holding of on merging this partially because of conflicts with #1132, and more generally because genPOI is scary, these changes are large, and none of us have had the time to sit down and test it. If anybody out there has the time and effort before we do, we'd really appreciate it.

**Comment by MasterofJOKers** [comment]
Thanks for the update.

Should I integrate the smaller changes of #1132 into this Pull Request? This would solve the conflicts ...

Also I'm using this code in production for standard POIs ever since I wrote it and tested it for manual POIs once.

**Comment by MasterofJOKers** [comment]
Also if you would like me to write some tests for this, please point me in a direction how to get started. I have not familiarized myself with overviewers testing, yet.

**Comment by agrif** [comment]
genPOI is something that desperately needs an overhaul, so I'm ok with not having automated tests. We're not exactly keeping up with them for the rest of the codebase, anyway.

If you're offering to do the integration, that'd be great.

**Comment by MasterofJOKers** [comment]
So I've added 3 commits for the code in #1132. All the other changes are already here.

**Comment by CounterPillow** [comment]
I've tested this with the following configuration. world1 is a singleplayer world, world2 a multiplayer world. All things seem to work as expected.

```python
worlds["world1"] = "/home/fratti/.minecraft/saves/markertest/"
worlds["world2"] = "/home/fratti/world/"

outputdir = "../jokergenpoi"

def signFilter(poi):
    if poi['id'] == 'Sign':
        return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])

def playerIcons(poi):
    if poi['id'] == 'Player':
        poi['icon'] = "http://overviewer.org/avatar/%s" % poi['EntityId']
        return "Last known location for %s" % poi['EntityId']

renders["world1_day"] = {
    "title":"World 1 Day",
    "world":"world1",
    "markers":[ dict(name="Signs", icon="signpost.png", filterFunction=signFilter),
                dict(name="Players", filterFunction=playerIcons),]
}

renders["world1_day_rot"] = {
    "title":"World 1 Rotated Day",
    "world":"world1",
    "northdirection":"lower-right",
    "markers":[ dict(name="Signs", icon="signpost.png", filterFunction=signFilter),
        dict(name="Players", filterFunction=playerIcons),]
}

renders["world1_night"] = {
    "title":"World 1 Night",
    "world":"world1",
    "rendermode":"night",
    "markers":[ dict(name="Signs", icon="signpost.png", filterFunction=signFilter),
                dict(name="Players", filterFunction=playerIcons),]
}

renders["world1_nether"] = {
    "title":"World 1 Nether",
    "world":"world1",
    "dimension":"nether",
    "rendermode":nether,
    "markers":[ dict(name="Signs", icon="signpost.png", filterFunction=signFilter),
                dict(name="Players", filterFunction=playerIcons),]
}

renders["world1_cave"] = {
    "title":"World 1 Cave",
    "world":"world1",
    "rendermode":"cave",
}

renders["world2_day"] = {
    "title":"World 2 Day",
    "world":"world2",
    "markers":[ dict(name="Signs", icon="signpost.png", filterFunction=signFilter),
        dict(name="Players", filterFunction=playerIcons),]
}
    
renders["world2_night"] = {
    "title":"World 2 Night",
    "world":"world2",
    "rendermode":"night",
    "markers":[ dict(name="Signs", icon="signpost.png", filterFunction=signFilter),
        dict(name="Players", filterFunction=playerIcons),]
}
```

I haven't dug into the actual code as of yet in an attempt to spot any issues, but so far this seems pretty good and most certainly better than what is currently in genPOI.

If someone else, with more in-depth knowledge of Python's multiprocessing than I have, would quickly make sure that the code looks alright, then I think this can finally be merged.

**Comment by eminence** [comment]
So I merged this without a real review, but it seems like more and more people are running into the current limitations of genPOI.  Anyone who's had issues before are strongly encouraged to try out this latest version!

Thanks!

**Pull request merged**
