### PR TITLE
Add compatibility for 21w39a and 21w43a snapshots

### LINKED ISSUE #1982: Generating blank tiles when rendering 21w37a/21w38a snapshot
Has anyone else tried running Overviewer on a world from one of the latest snapshots?

My render seems to be executing but all the rendered tiles are blank (all the same filesize).

### PR DESCRIPTION
**Pull request by 26**
This pull request adds basic compatibility for 21w39a and 21w43a. In both these snapshots, changes were made to the way chunks are stored on disk.

It does not yet implement paletted biome's and I have not fully tested everything yet. However, a good-looking world seems to come out when I try to render a world created in 21w44a.

This pull request should fix #1982.

### CODE REVIEW

**Comment by 26** [comment]
I have tested this on a much larger world. The result can be seen on https://poldercraft.nl/renders/world_081121/. I think this is ready now.

**Comment by Hackaloken** [comment]
I just started up a vanilla 1.18 server; this fixed livemap generation for me 👍

**Comment by spacegriffin** [comment]
Does this also fix rendering for the new generation under y=0?

**Review by F-Node-Karlsruhe — APPROVED** [review]
Urgently needed fix for 1.18 release

**Comment by bagobones** [comment]
Would appreciate this for minimum support. Our player group is really excited about 1.18 since so much has changed.

**Comment by BenKennish** [comment]
Can this be accepted please so that I can run a render for my 1.18 world?

**Comment by BenKennish** [comment]
OK so the players on my server are getting impatient to see the rendered map for the new 1.18 world.  It's been a while since I did anything more than the basics with `git` so can someone advise me on how to get this code working on my server but in such a way that I can still upgrade to the latest official version of Overviewer when it's released (possibly with this PR or a variation of it)?

**Comment by elboletaire** [comment]
> OK so the players on my server are getting impatient to see the rendered map for the new 1.18 world. It's been a while since I did anything more than the basics with `git` so can someone advise me on how to get this code working on my server but in such a way that I can still upgrade to the latest official version of Overviewer when it's released (possibly with this PR or a variation of it)?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

**Pull request merged**
