### PR TITLE
Add support for Google Maps API key

### PR DESCRIPTION
**Pull request by mikewebkist**
The Google Maps JS API now requires an API key. This adds support for a "google_api_key" variable in the config file, which is then properly added to the index.html when it is generated.

### CODE REVIEW

**Comment by CounterPillow** [comment]
We're currently working towards porting everything to LeafletJS in #1311, so this gets a NACK for me since I hope we can definitely and finally drop Google Maps API very soon.

**Comment by KrzysztofJaneczko** [comment]
Could you please merge these changes? I'm surprised you rejected them in the first place.

**Comment by CounterPillow** [comment]
@KrzysztofJaneczko because I'm not sure how this will interact with local map viewing or domains that have been grandfathered in, and I'd rather have a breaking change be something that gets rid of Google Maps.

**Comment by rlightner** [comment]
Would love to see this merged in since work on Leaflet seems to be dead.

**Comment by monokrome** [comment]
This seems pretty cool. Any chance it'll ever be merged? or is there possibly a new solution to this problem since it has been quite a while?

**Comment by CounterPillow** [comment]
Google Maps API will be dead this year due to a requirement for a credit card, so we're switching to leaflet, which means this isn't needed.

**Comment by monokrome** [comment]
@CounterPillow How does a credit card requirement make it dead? I would be fine w/ that.

**Comment by CounterPillow** [comment]
@monokrome most people are not happy providing their credit card details just for loading one JS file that we are not allowed to distribute ourselves. We used a very small part of the Google Maps API, essentially just the JS components, and yet our users would've had to sign up for services as if they were going to run a business drawing things on top of Google's tiles.

Leaflet is a better solution. It doesn't require an account with a surveillance megacorporation to use it. It doesn't require our users to give said corporation their credit card details for a free service. We can distribute it ourselves. We can modify it to our liking. We can pin it to a specific version. We can use it without an internet connection.

**Comment by monokrome** [comment]
To be clear, I'm not trying to be a proponent of Google Maps here. I'm just trying to get this thing to work without needing a secondary script injecting API keys whenever files change. If the change to leaflet has made that possible, then I'm excited 😺

**Pull request closed without merging**
