### PR TITLE
Support for polyline and polygon

### PR DESCRIPTION
**Pull request by jsmienk**
- Added support for polyline POI using Leaflet;
- Added support for polygon POI using Leaflet;
- Added two example filter functions to create polylines and polygons from signs in-game.

### CODE REVIEW

**Comment by jsmienk** [comment]
I tried. Vim not working with me. New commits emerge...

**Comment by jsmienk** [comment]
New vim and git skills acquired

**Comment by CounterPillow** [comment]
Ok now you've just made the git history even worse by back-merging master instead of rebasing on top of it

**Comment by jsmienk** [comment]
Okay, that's not good. I am just trying to contribute. What is the best thing to do now? Copy changes into a new branch and delete this PR, creating a new one?

**Pull request closed without merging**
