### PR TITLE
Python 3 port

### PR DESCRIPTION
**Pull request by CounterPillow**
Many things work, some don't. ~~Notably, genPOI doesn't work~~, and there's some signedness comparison stuff going on in the C extension.

This also completely drops support for Python 2, as maintaining a C extension for both Python 2 and 3 is a pain and not worth it for the 9 months that Python 2 is still going to be supported upstream.

The documentation needs to be adjusted as well.

All of the few tests we have pass, and rendering a map works, both with a configuration file and without. We can also use optimizeimages.

What needs work:
- [x] documentation
  * [x] Update optimizeimages instructions
  * [x] Update build instructions
    - [x] Update Windows build instructions
    - [x] Update Linux build instructions
    - [x] Update macOS build instructions
    - [x] Update FreeBSD build instructions
- [x] genPOI
  * [x] Switch from optparse to argparse
  * [x] Update syntax and semantics to Python 3
- [x] build infrastructure
  - [x] Debian/Ubuntu
  - [ ] RHEL/Fedora/CentOS
  - [x] Windows
- [x] contrib scripts
  - [x] contributors.py
  - [x] cyrillic_convert.py
  - [x] gallery.py
  - [x] playerInspect.py
  - [x] png-it.py
  - [x] regionTrimmer.py
  - [x] rerenderBlocks.py
  - [x] testRender.py
  - [x] validateRegionFile.py

I also suggest that once this work is done, we bump the version number to 0.14 or something.

### CODE REVIEW

**Comment by SteadBytes** [comment]
@CounterPillow Awesome work so far! Would you like some assistance with this? I'd love to help move Overviewer to Python 3 :smile:

**Comment by CounterPillow** [comment]
Hi @SteadBytes,

thank you for your interest in contributing. One area that would probably be easy to get started in is scripts in the `contrib` folder. They're mostly self-contained, so don't need much knowledge of the Overviewer codebase to port. Evaluate whether they're still relevant, port them to Python 3 (dropping Python 2 support along the way) and test them.

The other area that needs some help but is arguably less exciting is testing the less used parts of Overviewer with all its strange options, be it manually or by writing unit tests for them. Custom rendermodes, multiple worlds, JPEG, you name it.

**Comment by SteadBytes** [comment]
Thanks @CounterPillow that sounds good to me 😁 I'll get to work on the `contrib` scripts first and then move on to some other unit tests, if I'm unsure about whether something is still relevant is it ok to check with you?

**Comment by CounterPillow** [comment]
@SteadBytes feel free to ask, there's been a lot of rewrites and partial rewrites in overviewer's history that I've mostly been around for so I might know whether something is no longer relevant.

**Comment by CounterPillow** [comment]
@SteadBytes I've targeted Python 3.4 as the minimum so far, but considering that has gone end-of-life three days ago I'd be cool with Python 3.5 too.

**Comment by SteadBytes** [comment]
@CounterPillow Ok great, I guess it'll be a good idea to branch off `python3-fun-times` and PR back to it? Then all to the python3 stuff can go into master at once from there

**Comment by CounterPillow** [comment]
@SteadBytes yes, that'd be the easiest way to coordinate development. Thanks!

**Comment by LePetitTim** [comment]
I was doing it but i did not do that much it, good job !
Do you need help btw ?

**Comment by SteadBytes** [comment]
Great @CounterPillow, I'll get to work! 😁

**Comment by LePetitTim** [comment]
Would not it be better to go to python 3.5 or even 3.6 ?

**Comment by LePetitTim** [comment]
I can do that : Switch from optparse to argparse

**Comment by CounterPillow** [comment]
>Would not it be better to go to python 3.5 or even 3.6 ?

Minimum requirement? Not really. If you run Overviewer, you should probably always use the latest stable Python version since they continually add performance improvements. A minimum requirement is mostly there to make it easier for some people on stable release cycle to install Overviewer without requiring third party Python builds for their operating system.

I don't think Python 3 releases have added much interesting exclusive new functionality since 3.4. We already use OrderedDicts where we need them, we don't make use of tons of Abstract Meta Classes, asyncio doesn't seem to be that wise for us considering we need to have synchronous rearrangement of tile quadtrees for some operations (especially when they get aborted) and writing files to disk isn't really the performance bottleneck anyway. `os.scandir()` might be useful, but seems like a very small benefit. Type hints are a hack.

If we don't really need anything from newer Python 3 releases, it doesn't make sense to artificially raise the limit with a version check.

**Comment by LePetitTim** [comment]
I see, thanks :+1: but https://docs.pytest.org/en/latest/py27-py34-deprecation.html

**Comment by SteadBytes** [comment]
@CounterPillow I have opened a Draft PR for the `contrib` scripts here https://github.com/overviewer/Minecraft-Overviewer/pull/1545 so it's clear what is being done :smile: . `contributors.py` completed so far :+1:

**Comment by SteadBytes** [comment]
@CounterPillow the `contrib/cyrillic_convert.py` script was introduced to solve a UTF-8 issue with signs (https://github.com/overviewer/Minecraft-Overviewer/issues/454) . With the move to Python3 and it's better encoding support could this be handled in genPOI thus removing the need for that script?

**Comment by LePetitTim** [comment]
So, what can i do ? :smile:

**Comment by SteadBytes** [comment]
@CounterPillow just `contrib/testRender.py` left to do in #1545 now :+1: . It's taken longer than expected to get the scripts easily/reasonably testable. Should be all done soon :smile:

**Comment by SteadBytes** [comment]
@CounterPillow #1545 is ready for review :smile: . The PR is into this branch as discussed :+1:

**Comment by CounterPillow** [comment]
Okay, so this is basically done aside from updating the builders in [Overviewer-Web](https://github.com/overviewer/Overviewer-Web/) and resolving the merge conflict during merging.

**Comment by SteadBytes** [comment]
@CounterPillow Is there anything else you'd like help with? I can take a look at updating the builders in [Overviewer-Web](https://github.com/overviewer/Overviewer-Web)? No worries if not :+1:

**Comment by CounterPillow** [comment]
@SteadBytes If you can get the docker swarm to work for you then yes, that'd be great. Personally, I can't get it to run properly. You might also need to make some changes to the code to make it work without AWS keys last I tried. It's a mess.

**Comment by SteadBytes** [comment]
@CounterPillow Ok I'll see what I can do :+1: I should get a chance to take a look either tonight or tomorrow

**Comment by SteadBytes** [comment]
Making progress with Overviewer-Web :sweat-smile: In addition to moving to Python3 am I ok to do some refactoring of the Buildbot configuration to make local dev easier/possible?

**Comment by CounterPillow** [comment]
>In addition to moving to Python3 am I ok to do some refactoring of the Buildbot configuration to make local dev easier/possible?

Please do! That would be excellent

**Comment by SteadBytes** [comment]
Ok will do, I'm currently doing battle with the Makefiles to be compatible with the latest version of GnuPG, I looks like they were written for GnuPG v1 and re-building the images pulls down v2 which is causing problems. It'll be good to update the the latest GnuPG version anyway so it's probably a good thing :joy:

**Comment by SteadBytes** [comment]
@CounterPillow the config for Overviewer Web has many occurrences of `exmaple` such as https://github.com/overviewer/Overviewer-Web/blob/master/buildbot/master.cfg#L45 . I suspect this is a typo but I want to check that it's not an acronym or something that I am not aware of. Do you know whether it's just a typo? Cheers

**Comment by CounterPillow** [comment]
@SteadBytes It's not a typo, it's the name of our example map.

**Comment by SteadBytes** [comment]
Oh yes of course, I knew that as well. Clearly my brain wasn't putting the two together haha :sweat_smile:  Thank you!

**Comment by SteadBytes** [comment]
@CounterPillow I have found an issue with getting the version from `setup.py`. Part of the builbot config uses the command `python3 setup.py --version` to extract the Overviewer version to use when building packages. However, on this branch that command outputs `unknown`. My initial guess is that it's something to do with https://github.com/overviewer/Minecraft-Overviewer/blob/python3-fun-times/setup.py#L66 . Any ideas? :thinking:

**Comment by CounterPillow** [comment]
@SteadBytes Make sure git is installed and the source directory is a git clone, since `findGitVersion` tries to Popen git.

**Comment by SteadBytes** [comment]
@CounterPillow Yep, git is definitely installed and the source directory is a git clone. I can replicate the issue both in the docker containers for Overviewer-Web and just on my machine after checking out this branch.

This issue is to do with `p.stdout.readlines()` returning `bytes` objects and not strings [source](https://github.com/overviewer/Minecraft-Overviewer/blob/e348a548b6cce2af2066db243b3c4d76ec40de32/overviewer_core/util.py#L63) . I'll put together a fix for this and other places using `Popen` in a similar way and PR to this branch :+1:

**Comment by agrif** [comment]
Just wanted to pop in to thank you all for working on this. Y'all are awesome.

**Comment by SteadBytes** [comment]
@agrif Hey thank you, I really appreciate that and thank you for all the work you've done on this project! Hopefully this'll be ready to go soon, the build system is coming along well and I'll try to get it finished up ASAP :+1:

**Comment by agrif** [comment]
I've merged the changes to `master` since this branch started. Tomorrow (*crosses fingers*) I'll merge the build system and make sure it's all working together. Thanks again!

**Comment by agrif** [comment]
That should do it! Thanks!

**Comment by enaut** [comment]
There is one TODO left to do: buildscripts for rpm based distros. If you are interested, I updated my copr Repos to build for Fedora+CentOS.

The rpm spec file is here: https://github.com/enaut/Minecraft-Overviewer/blob/weekly-tito/Minecraft-Overviewer.spec

You are free to use any of this (or my branch) or the copr repos.

**Comment by CounterPillow** [comment]
that's actually done already, I just forgot to check it

**Pull request merged**
