### PR TITLE
WIP: Add support for Bedrock maps

### LINKED ISSUE #921: request support for pocket and bedrock edition maps
$ overviewer.py --rendermodes=smooth-lighting "world1" ./
2013-04-24 16:29:56  Welcome to Minecraft Overviewer!
2013-04-24 16:29:56 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 532, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 413, in main
    w = world.World(render['world'])
  File "/usr/lib/python2.7/dist-packages/overviewer_core/world.py", line 97, in **init**
    data = nbt.load(os.path.join(self.worlddir, "level.dat"))[1]['Data']
  File "/usr/lib/python2.7/dist-packages/overviewer_core/nbt.py", line 29, in wrapper
    return func(fileobj, *args)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/nbt.py", line 37, in load
    return NBTFileReader(fileobj).read_all()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/nbt.py", line 181, in read_all
    tagtype = ord(self._file.read(1))
  File "/usr/lib/python2.7/gzip.py", line 256, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 291, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 185, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

### PR DESCRIPTION
**Pull request by barrett777**
I'm working on adding support for Bedrock maps (Fixes #921).  This pull request is not ready for review, I'm just opening it as a spot to show my code and ask for help.  I've hit a problem with rendering and I'm not sure what isn't working.

If someone can help me get past this rendering issue, I can keep going and hopefully do most of the remaining bits on my own.

**My problem:** All my output png renders are fully transparent pngs.  I believe all the chunks/subchunks are being "rendered", but no blocks are drawn.

Here's where I'm at:

**Imported code**
Mojang leveldb dlls via BSD3-Clause: https://github.com/Mojang/leveldb-mcpe
This MIT library for reading chunks and blocks from leveldb: https://github.com/BluCodeGH/bedrock
(Includes bedrock.py, leveldb.py, and nbd2.py)

**Code changes in Overviewer**
Nearly all my changes are in nbt.py and world.py:

Bedrock data is stored in one leveldb database - there's no concept of RegionFiles, so I just store everything in one 'RegionFile' in Overviewer.

I am able to iterate all chunks by checking for chunk keys in leveldb.

I'm not yet able to check when a chunk was last modified, so for now 'get_chunk_timestamp' just returns the current time.  I think this is just used to check if Overviewer can skip re-rendering images that haven't changed, so I don't think this should cause problems at this time.

I don't read from 'level.dat' file.  There is a 'level.dat' file in Bedrock, but it's not the same as the Anvil one, so I'm just skipping this for now.  I don't think this was required for rendering a map.

I can't yet find the 'true spawn', so I just return (0, 0, 0).  I think this is stored in 'level.dat' so it is something I can find later.  I think this is low priority though.

I can find each block's type such as 'minecraft:bedrock', and Anvil and Bedrock share most of these (hooray!).  For now I'm replacing any unrecognized blocks with 'minecraft:bedrock' (world.py line 884).  I just want to get something rendering before I start working through these specific differences.

At this time I'm not worrying about block data.  I'm not sure if Bedrock and Anvil have the same data formats or not, I haven't yet checked.  I think this is optional stuff though such as what direction rails are facing.

Bedrock does store chunk 'biome' data, but I don't know what that is.  At this time I'm just passing it through the existing Overviewer biome code, and it doesn't blow up, so maybe that is okay. (world.py line 1361)

I don't think Bedrock stores chunk skylight or blocklight data, and I'm suspicious that this may be the cause of my render problems.  I've tried changing rendermode to 'normal' to attempt to avoid trying to use that lighting data.  I've tried initializing skylight and blocklight to 255 which I think is full lighting for every chunk.  I'm not sure what else to do. (world.py line 1411)

This implementation of leveldb doesn't support multiple threads, so at this time you need to set 'processes' to 1 or it will blow up.  I'm sure I can get it to work on multiple threads in the future though.

Here's a sample new Bedrock map: https://drive.google.com/open?id=1HX-mFZFm1N0jKIQA3s8NMqbRa9kZe1yJ

More info on leveldb key/value formats: https://minecraft.gamepedia.com/Bedrock_Edition_level_format

### CODE REVIEW

**Comment by ThomasRunting** [comment]
have a look how https://github.com/mjungnickel18/papyruscs is doing it

**Comment by centuryx476** [comment]
More and more people are playing bedrock. 
It be great if support can be added. 
I'm not much of a python developer

**Comment by quizhizhe** [comment]
I think there is no skylight, so it can't render normally

**Comment by supergnaw** [comment]
I'm looking to revive this, but your google link has expired so I'm not sure where you left off. Could you give me some insight?

**Comment by barrett777** [comment]
@supergnaw That would be great! :)

I haven't made any progress since this PR, so you can take whatever you want from this if it is helpful

The google drive link was just a plain new Bedrock map.  You can just create a new one in the game client or use an existing save.

**Comment by centuryx476** [comment]
> 
> 
> I'm looking to revive this, but your google link has expired so I'm not sure where you left off. Could you give me some insight?

Fantastic!!!!

**Comment by quizhizhe** [comment]
The texture package structure(or NBT data?) of JE and BE is different. Maybe you have to modify the part that reads the texture package.  Overviewer uses JE texture packs by default

**Comment by centuryx476** [comment]
Glad this is now being worked on.

**Comment by barrett777** [comment]
Yeah I'm making some actual progress which is good.  I'll probably ask for help later.  I'll probably have something to show in a couple weeks

**Comment by barrett777** [comment]
I'm making good progress but stuck again.  I'll close and reopen a new PR asking for help

**Comment by barrett777** [comment]
Here's a new PR if anyone is able to help: #2044

**Pull request closed without merging**
