### PR TITLE
add support for advpng to optimizeimages.py

### PR DESCRIPTION
**Pull request by mc680x0**
AdvPNG, working in conjunction with OptiPNG, can produce better results than either tool alone; this commit permits advpng to be used from the overviewer.

### CODE REVIEW

**Comment by eminence** [comment]
FYI:  you didn't need to close your first PR (#1247) -- you can just push more commits to the branch and the PR will update automatically.

**Comment by mc680x0** [comment]
Ah, I didn't realise github would presume that. Thanks.

**Comment by awilfox** [comment]
:+1: Every little bit helps on data sets this large, it works here.

**Comment by agrif** [comment]
Half a year later, we've merged this code. Sorry for the wait!

Thank you for your contribution!

**Pull request merged**
