### PR TITLE
fixed dead navigation on iOS on iPhone and iPad. 

### PR DESCRIPTION
**Pull request by mtoensing**
This fixes navigation not working on iOS Safari on iPad and iPhone.

### CODE REVIEW

**Comment by CounterPillow** [comment]
Thanks for looking into this

**Comment by xcjs** [comment]
@mtoensing I'm not involved with the project, but they may not be ready to merge the 113 branch in as it still incorrectly renders a number of blocks. See #1486 for some examples.

**Comment by mtoensing** [comment]
@xcjs You were wrong =D

**Comment by xcjs** [comment]
@mtoensing I'm still seeing the same issues on the minecraft113 branch as of a few days ago. Are you sure this had changed?

**Comment by CounterPillow** [comment]
well, the minecraft113 branch no longer is a thing so I'm not sure what you're using

**Comment by xcjs** [comment]
@CounterPillow

The branch is still showing up in the drop-down for me. Is it deprecated now?

**Comment by xcjs** [comment]
I see that @mtoensing had his own minecraft113 branch - should the minecraft113 branch in this remote be closed now? I've seen more than one other user mention running from this remote's branch.

**Comment by mtoensing** [comment]
Oh, i will delete my fork right away.

**Comment by mtoensing** [comment]
done.

**Comment by xcjs** [comment]
@mtoensing 

It looks like this repository still has the old minecraft113 branch. Does this repository keep all branches, or is it time to clean those out?

**Comment by CounterPillow** [comment]
I've deleted the minecraft113 branch like 2 days ago.

**Comment by xcjs** [comment]
@CounterPillow Apologies - I had a stale browser tab open still. Thanks for cleaning up.

**Comment by xcjs** [comment]
@mtoensing

All things considered in #1486, was I still so wrong?

Though I am glad a partially functional version was released at opposed to none at all.

**Comment by mtoensing** [comment]
We were both wrong. I think that a 113 Version with these problems is better than non at all. But there are some issues that needs to be addressed. My hope is now that this is the current version there is more pressure on solving the missing block problems.

**Pull request merged**
