### PR TITLE
Update setup.py to setuptools

### PR DESCRIPTION
**Pull request by AstraLuma**
Forward-ports the setup.py changes from https://github.com/overviewer/Minecraft-Overviewer/pull/1208 to the current version.

This specifically allows building wheels for overviewer.

### CODE REVIEW

**Comment by astronouth7303** [comment]
For the record, I'm using this to build a overviewer container in https://github.com/minecraft-podman/container-server

**Comment by astronouth7303** [comment]
Any commentary?

**Comment by astronouth7303** [comment]
Sorry to keep bothering about this.

**Comment by CounterPillow** [comment]
Sorry for the long wait, I'll get around to testing and merging this soon!

**Comment by CounterPillow** [comment]
Thanks, merged. I added one small change: not locally finding PIL is not a fatal error. It may still be in e.g. /usr/include. Better to just try anyway.

**Comment by CounterPillow** [comment]
Turns out I'll have to revert this, I think. It completely breaks buildbot in various ways:

http://overviewer.org/build/#/

Some sample failures:
- weird sdist stuff? http://overviewer.org/build/#/builders/2/builds/188
- more weird sdist stuff http://overviewer.org/build/#/builders/1/builds/154
- no longer finding PIL http://overviewer.org/build/#/builders/2/builds/187

**Comment by CounterPillow** [comment]
I'll look into this again later, I currently am not in the right state of things (no alcohol in the house) to tackle buildbot failures

**Pull request merged**
