### PR TITLE
[WEB] JS Fixes

### PR DESCRIPTION
**Pull request by DevScyu**
Added support for Polygons, Polylines and Fixed a bug where you could scroll to a minimum zoom level of 0, even if in the config it was set at a higher number.

Fixed the code for 
```js
overviewer.util.ready(function(){
    // do stuff
});
```

See the changes in action: http://wynndata.tk/map/

### CODE REVIEW

**Comment by r15ch13** [comment]
👍 for the  `overviewer.util.ready();` fix

**Comment by CounterPillow** [comment]
Sorry that I haven't gotten around to reviewing this yet, I'll try to get it done within the next 7 days.

**Comment by DevScyu** [comment]
I have been working on the Leaflet map for a while so any questions or changes feel free to ask.

**Comment by SkylixMC** [comment]
In reference to the bug where you could zoom past the number set in the config, though now it is fixed for the most part, still if you switch to another world, the world loads so it IS zoomed past the min zoom. You have to zoom back in to fix it.

**Pull request closed without merging**
