### PR TITLE
Add Composter block

### PR DESCRIPTION
**Pull request by Avaren**

### CODE REVIEW

**Comment by Avaren** [comment]
@IncredibleHolg you seem to be a block adding expert, would you mind checking I've done this correctly?

**Comment by IncredibleHolg** [comment]
@Avaren I will handle this.
I am at the moment  adding bamboo and will integrate your changes in this pull request.

**Comment by IncredibleHolg** [comment]
Linked this to #1613

**Comment by IncredibleHolg** [comment]
You did not map the palette_entry['Properties']['level'] value to the data value,
so only the data=0 texture was used.

```diffdiff --git a/overviewer_core/world.py b/overviewer_core/world.py
index 04f723e..4db4151 100644
--- a/overviewer_core/world.py
+++ b/overviewer_core/world.py
@@ -1129,6 +1129,8 @@ class RegionSet(object):
                 data = 1
             else:
                 data = 0
+        elif key == "minecraft:composter":
+            data = palette_entry['Properties']['level']
         return (block, data)
```

**Comment by IncredibleHolg** [comment]
Please close this pull request, your code is merged into #1668

**Pull request closed without merging**
