### PR TITLE
1.16 Updates and Misc.

### PR DESCRIPTION
**Pull request by Doregon**
This is a collective pull request containing the following:

* @IncredibleHolg's work with 1.16 blocks.
  * described on #1807 
* @dreamwraith's work of merging @IncredibleHolg's work into one branch.
  * described on #1856 
* My work updating the docs/using.rst file.
  * described on #1900 

This is different from previous pull requests and better than just merging from 116-blocks -> master because it also contains the latest version of Overviewer (0.16.13) with the latest code. This will also receive changes every week if new commits are pushed to `overviewer:master` (so when ready to merge, this fork will already be up to date).

### CODE REVIEW

**Comment by drnixon** [comment]
Thank you for merging these into one request. I've been watching the requests from IncredibleHolg and have been concerned that the delay between submitting and actually getting them merged and implemented would discourage further work from him.

**Comment by Doregon** [comment]
Of course! I hope that someone ends up merging these, all of the issues in here (meaning, the lack of 1.16 blocks and the missing "don't render while open" section) are over 6 months old by now and nothing is happening with them. I ran into these exact problems too!

**Comment by Doregon** [comment]
I may also start working on the oil branch and bringing it up-to-date with 0.16.12. That seemed like a good plan and I might start working on it (because it would be nice for my GPU to handle renders, and my CPU to handle everything else). That will either be a part of this pull (if this pull is still open) or a new one.

**Review by Depado — APPROVED** [review]

**Review by bold-gman — APPROVED** [review]

**Review by Depado — APPROVED** [review]

**Comment by Timamling90** [comment]
is there a compiled version for Windows?

**Comment by bold-gman** [comment]
As this PR is not merged into the master branch, there are no prebuild releases yet. But I successfully built from source on Windows and Ubuntu as described in the official documentation:

For Windows I used these steps: http://docs.overviewer.org/en/latest/building/#building-with-mingw-w64-and-msys2 

Just remember to clone @Doregon's repo instead of the official, at least for now:
git clone https://github.com/Doregon/Minecraft-Overviewer.git

**Comment by CounterPillow** [comment]
Closing this since I already merged IncredibleHolg's PR

**Pull request closed without merging**
